<a href="https://colab.research.google.com/github/ilirsheraj/DUDL/blob/main/Chapter_09_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#DataSet Loader

In [1]:
# Import Libraries
import numpy as np
import torch
from torch.utils.data import DataLoader, TensorDataset

In [2]:
# Create a dataset in Numpy
nObservations = 100
nFeatures = 20

data = np.random.randn(nObservations, nFeatures)

data.shape

(100, 20)

In [3]:
# Convert the data into pytorch tensor
dataT = torch.tensor(data)

# Print out some information
print("Numpy Data")
print(type(data))
print()
print(data.shape) # numpy -> .shape
print()
print(data.dtype) # The 

Numpy Data
<class 'numpy.ndarray'>

(100, 20)

float64


In [4]:
print("Tensor Data")
print(type(dataT))
print()
print(dataT.size()) # torch -> size() dataT.shape also works
print()
print(dataT.dtype)

Tensor Data
<class 'torch.Tensor'>

torch.Size([100, 20])

torch.float64


In [5]:
# Converting datatypes
dataT2 = torch.tensor(data).float()
print(dataT2.dtype)

torch.float32


In [6]:
# .long() works for integers, like we have always used to create labels
dataT3 = torch.tensor(data).long()
print(dataT3.dtype)

torch.int64


In [7]:
data

array([[-0.82976739,  0.34754678,  1.39177293, ..., -0.10090905,
        -2.40662971, -0.93024654],
       [-0.47078504, -1.2031652 , -0.29491722, ..., -0.33086413,
        -2.03526516, -0.1693245 ],
       [-0.36169913,  0.89359374,  1.30586172, ...,  0.54162879,
         1.13778047,  0.71966624],
       ...,
       [-1.77784199, -0.7895438 , -0.09308796, ..., -0.75162999,
         0.33888008, -0.83388868],
       [ 0.97350813, -0.21948429,  1.00061519, ...,  0.10455374,
        -0.07579497,  2.94497991],
       [ 0.18612095,  0.63066434,  1.01978561, ...,  0.2509639 ,
         0.13576483,  0.29997071]])

In [9]:
dataT2

tensor([[-0.8298,  0.3475,  1.3918,  ..., -0.1009, -2.4066, -0.9302],
        [-0.4708, -1.2032, -0.2949,  ..., -0.3309, -2.0353, -0.1693],
        [-0.3617,  0.8936,  1.3059,  ...,  0.5416,  1.1378,  0.7197],
        ...,
        [-1.7778, -0.7895, -0.0931,  ..., -0.7516,  0.3389, -0.8339],
        [ 0.9735, -0.2195,  1.0006,  ...,  0.1046, -0.0758,  2.9450],
        [ 0.1861,  0.6307,  1.0198,  ...,  0.2510,  0.1358,  0.3000]])

In [10]:
dataT3

tensor([[ 0,  0,  1,  ...,  0, -2,  0],
        [ 0, -1,  0,  ...,  0, -2,  0],
        [ 0,  0,  1,  ...,  0,  1,  0],
        ...,
        [-1,  0,  0,  ...,  0,  0,  0],
        [ 0,  0,  1,  ...,  0,  0,  2],
        [ 0,  0,  1,  ...,  0,  0,  0]])