<a href="https://colab.research.google.com/github/ilirsheraj/DUDL/blob/main/Chapter_06_regularization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

## Regular Dropout

In [2]:
# Define a dropout instance and create some data
# define the probability
prob = 0.5 # default

dropout = nn.Dropout(p=prob)
dropout

Dropout(p=0.5, inplace=False)

In [11]:
# Lets see what dropout returns
x = torch.ones(10)

y = dropout(x)
print(x)
print()
print(y) # y/(1-p), SCALED UP
print()
print(torch.mean(y))
# Independent probabilities

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

tensor([2., 0., 2., 0., 2., 2., 2., 0., 0., 0.])

tensor(1.)


In [14]:
# dropout is turned off when evaluating the model
dropout.eval()
# All lines within its identation will have dropout mode off
y = dropout(x)
print(y)
print(torch.mean(y))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor(1.)


In [15]:
# Another way to use dropout is to use F.dropout()
dropout.eval()
y = F.dropout(x) # no need to specify instance
print(y)
print()
print(torch.mean(y))

tensor([2., 0., 2., 0., 0., 2., 0., 0., 0., 2.])

tensor(0.8000)


In [16]:
# We can manually switch it off with F
dropout.eval()
y = F.dropout(x, training=False)
print(y)
print()
print(torch.mean(y))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

tensor(1.)


In [17]:
# When a model is switched to eval mode it stays in it until it is switched back to training mode
dropout.train()
y = dropout(x)
print(y)
print()

dropout.eval()
y = dropout(x)
print(y)
print()

# dropout.train()
y = dropout(x) # will still be in eval unless dropout.train() is activated
print(y)

tensor([2., 0., 2., 0., 2., 0., 2., 0., 0., 0.])

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
